server:
  port: 9090

spring:
  datasource:
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/online_learning?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#  datasource:
#    username: online_learning
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://43.143.121.13:3306/online_learning?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai

  application:
    name: online_learning
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1000MB
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
